all :
	#Python does not need to compile but gradescope requires something here
	#So we just output a placeholder message to the terminal
	echo "Python does not need to compile!"

	#runs your code. You can change main.py to the name of your main python file if you need to.
run :
	python3 SortingDriver.py
