all :
	#Gradescope will use g++ to compile. You can change the -std flag to a higher standard if you need to.
	#makesure the a.out in the line matches the one under the run target if you change it
	g++ -std=c++11 -o a.out *.cpp

	#Simply run the executable that was compiled. Needs to match the name after the -o flag above.
run :	
	./a.out
