all :
	#Simply call javac and compile all java files in the current directory
	#You shouldn't need to change this.
	javac -cp lib/*:. *.java

	#Change line below to match the name of your java file that contains your main() method.
	#OR just make sure to call your main file Main.java
run :
	java SortingDriver
